//Login Reducers Type
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//LOST and Found Reducers
// Lost Report Reducers
export const ADD_LOST_REPORT = 'ADD_LOST_REPORT';
export const GET_LOST_REPORTS = 'GET_LOST_REPORT';
export const REPORT_LOADING = 'REPORT_LOADING';
export const SET_REPORT_TO_FOUND = 'SET_REPORT_TO_FOUND';
export const SET_REPORT_TO_CLAIMED = 'SET_REPORT_TO_CLAIMED';
// Found Report Reducers
export const GET_FOUND_REPORTS = 'GET_FOUND_REPORTS';
export const ADD_FOUND_REPORT = 'ADD_FOUND_REPORT';
export const DELETE_FOUND_REPORT = 'DELETE_FOUND_REPORT ';

// OrgDesc Reducers 
export const GET_ORGDESC = 'GET_ORGDESC';
export const ADD_ORGDESC = 'ADD_ORGDESC';
export const UPDATE_ORGDESC = 'UPDATE_ORGDESC';
export const DELETE_ORGDESC = 'DELETE_ORGDESC';
export const RECORD_LOADING = 'RECORD_LOADING';

// OrgAccnts Reducers
export const GET_ORG_ACCNTS = 'GET_ORG_ACCNTS';
export const REGISTER_ORG_ACCNT = 'REGISTER_ORG_ACCNT';
export const ACCNTS_LOADING = 'ACCNTS_LOADING';

//Id Replacement reducers
export const GET_ID_REPLACEMENTS = 'GET_ID_REPLACEMENTS';
export const ADD_ID_REPLACEMENT = 'ADD_ID_REPLACEMENT';
export const ID_FETCHED_BY_ID = 'ID_FETCHED_BY_ID';
export const UPDATE_ID_REPLACEMENT = 'UPDATE_ID_REPLACEMENT';
export const ID_REPLACEMENT_LOADING = 'ID_REPLACEMENT_LOADING';

//Request Activity Reducers
// Org Part 
export const GET_ORG_FEEDS = 'GET_ORG_FEEDS';
export const GET_REQUEST_ACTIVITIES = 'GET_REQUEST_ACTIVITIES';
export const SUBMIT_REQUEST_ACTIVITIES = 'SUBMIT_REQUEST_ACTIVITIES';
export const REQUEST_ACTIVITIES_LOADING = 'REQUEST_ACTIVITIES_LOADING';
// SOA Head Part 
export const COUNT_REQUEST_ACTIVITIES_NOTIF = 'COUNT_REQUEST_ACTIVITIES_NOTIF';
export const GET_REQUEST_ACTIVITIES_HEAD = 'GET_REQUEST_ACTIVITIES_HEAD';
export const UPDATE_COUNT_NOTIF = 'UPDATE_COUNT_NOTIF';
export const SET_APPROVED_REQUEST_ACTIVITIES_HEAD = 'SET_APPROVED_REQUEST_ACTIVITIES_HEAD';
export const SET_DECLINED_REQUEST_ACTIVITIES_HEAD = 'SET_DECLINED_REQUEST_ACTIVITIES_HEAD';
//SOA Admin Reduceres
export const SET_APPROVED_REQUEST_ACTIVITIES_ADMIN = 'SET_APPROVED_REQUEST_ACTIVITIES_ADMIN';
export const SET_DECLINED_REQUEST_ACTIVITIES_ADMIN = 'SET_DECLINED_REQUEST_ACTIVITIES_ADMIN';

//Announcements reducers
export const ADD_ANNOUNCEMENT_ADMIN = 'ADD_ANNOUNCEMENT_ADMIN';
export const ADD_ANNOUNCEMENT_ADMIN_FALSE = 'ADD_ANNOUNCEMENT_ADMIN_FALSE';
export const UPDATE_ANNOUNCEMENT_ADMIN = 'UPDATE_ANNOUNCEMENT_ADMIN';
export const UPDATE_ANNOUNCEMENT_ADMIN_FALSE = 'UPDATE_ANNOUNCEMENT_ADMIN_FALSE';
export const DELETE_ANNOUNCEMENT_ADMIN = 'DELETE_ANNOUNCEMENT_ADMIN';
export const DELETE_ANNOUNCEMENT_ADMIN_FALSE = 'DELETE_ANNOUNCEMENT_ADMIN_FALSE';

export const ADD_ANNOUNCEMENT_HEAD = 'ADD_ANNOUNCEMENT_HEAD';
export const ADD_ANNOUNCEMENT_HEAD_FALSE = 'ADD_ANNOUNCEMENT_HEAD_FALSE';
export const UPDATE_ANNOUNCEMENT_HEAD = 'UPDATE_ANNOUNCEMENT_HEAD';
export const UPDATE_ANNOUNCEMENT_HEAD_FALSE = 'UPDATE_ANNOUNCEMENT_HEAD_FALSE';
export const DELETE_ANNOUNCEMENT_HEAD = 'DELETE_ANNOUNCEMENT_HEAD';
export const DELETE_ANNOUNCEMENT_HEAD_FALSE = 'DELETE_ANNOUNCEMENT_HEAD_FALSE';
