//Login Reducers Type
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//LOST and Found Reducers
// Lost Report Reducers
export const ADD_LOST_REPORT = 'ADD_LOST_REPORT';
export const GET_LOST_REPORTS = 'GET_LOST_REPORT';
export const REPORT_LOADING = 'REPORT_LOADING';
export const SET_REPORT_TO_FOUND = 'SET_REPORT_TO_FOUND';
export const SET_REPORT_TO_CLAIMED = 'SET_REPORT_TO_CLAIMED';
// Found Report Reducers
export const GET_FOUND_REPORTS = 'GET_FOUND_REPORTS';
export const ADD_FOUND_REPORT = 'ADD_FOUND_REPORT';
export const DELETE_FOUND_REPORT = 'DELETE_FOUND_REPORT ';

// OrgDesc Reducers 
export const GET_ORGDESC = 'GET_ORGDESC';
export const ADD_ORGDESC = 'ADD_ORGDESC';
export const UPDATE_ORGDESC = 'UPDATE_ORGDESC';
export const DELETE_ORGDESC = 'DELETE_ORGDESC';
export const RECORD_LOADING = 'RECORD_LOADING';

// OrgAccnts Reducers
export const GET_ORG_ACCNTS = 'GET_ORG_ACCNTS';
export const REGISTER_ORG_ACCNT = 'REGISTER_ORG_ACCNT';
export const ACCNTS_LOADING = 'ACCNTS_LOADING';

//Id Replacement reducers
export const GET_ID_REPLACEMENTS = 'GET_ID_REPLACEMENTS';
export const ADD_ID_REPLACEMENT = 'ADD_ID_REPLACEMENT';
export const ID_FETCHED_BY_ID = 'ID_FETCHED_BY_ID';
export const UPDATE_ID_REPLACEMENT = 'UPDATE_ID_REPLACEMENT';
export const ID_REPLACEMENT_LOADING = 'ID_REPLACEMENT_LOADING';

//Request Activity Reducers
export const GET_ORG_FEEDS = 'GET_ORG_FEEDS';
export const GET_REQUEST_ACTIVITIES = 'GET_REQUEST_ACTIVITIES';
export const SUBMIT_REQUEST_ACTIVITIES = 'SUBMIT_REQUEST_ACTIVITIES';
export const REQUEST_ACTIVITIES_LOADING = 'REQUEST_ACTIVITIES_LOADING';